version: "3.8"

services:
  pfdb:
    image: yobasystems/alpine-mariadb
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_PASSWORD
      MYSQL_DATABASE: pf
      #- MYSQL_ROOT_PASSWORD=sheep
    networks:
      test-pf:
    volumes:
     - db_data:/var/lib/mysql
     - ./pathfinder/export/sql/eve_universe.sql.zip:/eve_universe.sql.zip
    restart: always
    logging:
      driver: none
  pf-redis:
    image: redis:latest
    command: redis-server /usr/local/etc/redis/redis.conf
    hostname: redis
    volumes:
      - redis_data:/data
      - ./config/pathfinder/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      test-pf:
    logging:
      driver: none
    restart: always
  pf-socket:
    image: composer:latest
    command: ["sh","-c","composer install && php cmd.php --tcpHost 0.0.0.0"]
    hostname: socket
    logging:
      driver: none
    volumes:
      - ./websocket:/app
    networks:
      test-pf:
    restart: always
  pf:
    hostname: "pathfinder"
    build: '.'
    env_file:
    - .env
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.testpf.loadbalancer.server.port=80"
      - "traefik.http.routers.testpf.tls=true"
      - "traefik.http.routers.testpf.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.testpf.entrypoints=websecure"
      - "traefik.docker.network=web" # put your traefik network web/proxy/whatever you use here
    networks:
      - test-pf
      - web
        #ports:
        #- 5000:80
        #- 8030:8030
    healthcheck:
      disable: true
    tty: true
    volumes:
      - ./config/pathfinder/config.ini:/var/www/html/pathfinder/app/templateConfig.ini
      - ./config/pathfinder/routes.ini:/var/www/html/pathfinder/app/routes.ini
      - ./config/pathfinder/pathfinder.ini:/var/www/html/pathfinder/conf/pathfinder.ini
      - ./config/pathfinder/plugin.ini:/var/www/html/pathfinder/app/plugin.ini
    depends_on:
      - pfdb   
      - pf-redis
      - pf-socket
    restart: always

volumes:
     data:
     db_data:
     redis_data:
networks:
    test-pf:
    web:
       external: true

